config/routes.rb
Iact::Application.routes.draw do
  root to: 'main_page#home'
	
	match '/help',    to: 'main_page#help'
	match '/about',   to: 'main_page#about'
	match '/contact', to: 'main_page#contact'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  
  before_save { |user| user.email = email.downcase }
  
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "iACT Online"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    iACT Online by Giovanni Coia
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "iACT", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "Help",    help_path %></li>
              <li><%= link_to "Sign in", '#' %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/main_page/about.html.erb
<% provide(:title, 'About iACT') %>
<h1>About iACT</h1>
<p>
  iACT is an smartphone application to aid in the delivery of Acceptance and Commitment Therapy.
</p>

app/views/main_page/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact iACT at 1105874C@student.gla.ac.uk
</p>

app/views/main_page/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Help coming soon!
</p>

app/views/main_page/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to iACT Online</h1>

  <h2>
    This is the home page for the iACT online interface
  </h2>

  <%= link_to "Sign In", '#', class: "btn btn-large btn-primary" %>
</div>